import {routeUrl,currentPath} from './hosting.js';
import React,{createContext,useContext,useEffect,useState,useRef} from 'react';
import {X,LoaderCircle,CheckCircle2,AlertCircle} from 'lucide-react';
export const AppContext=createContext(null);
export const useApp=()=>useContext(AppContext);
export const money=(n,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n||0)/100);
export const date=x=>x?new Date(x).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
export const initials=n=>(n||'?').split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase();
export function Link({to,children,...props}){return <a href={routeUrl(to)} {...props} onClick={e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();history.pushState({},'',routeUrl(to));window.dispatchEvent(new PopStateEvent('popstate'));props.onClick?.(e)}}>{children}</a>}
export function navigate(to){history.pushState({},'',routeUrl(to));window.dispatchEvent(new PopStateEvent('popstate'));}
export function usePath(){const [path,set]=useState(currentPath);useEffect(()=>{const cb=()=>set(currentPath());window.addEventListener('popstate',cb);window.addEventListener('hashchange',cb);return()=>{window.removeEventListener('popstate',cb);window.removeEventListener('hashchange',cb)}},[]);return path;}
export function useData(path,deps=[]){const {api,workspace,revision}=useApp();const [data,set]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);setError('');api(path).then(d=>active&&set(d)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[path,workspace,revision,...deps]);return {data,error,loading,set};}
export function Loading(){return <div className="state"><LoaderCircle className="spin" size={25}/><p>Loading your workspace…</p></div>}
export function Empty({title='Nothing here yet',text='Add your first record to get started.',children}){return <div className="state empty"><span className="empty-symbol">✧</span><h3>{title}</h3><p>{text}</p>{children}</div>}
export function ErrorBox({children}){return children?<div className="error" role="alert"><AlertCircle size={18}/>{children}</div>:null;}
export function Badge({children}){return <span className={'badge '+String(children||'').toLowerCase().replaceAll(' ','-')}>{children}</span>}
export function Modal({title,children,onClose,wide=false}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;ref.current?.querySelector('input,button,select,textarea')?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const list=ref.current.querySelectorAll('button,input,select,textarea,a[href]');const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();}},[]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X/></button></div>{children}</section></div>}
export function Form({children,onSubmit,label='Save changes',onCancel}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSubmit(Object.fromEntries(new FormData(e.currentTarget)));}catch(e){setError(e.message);}finally{setBusy(false)}}}><ErrorBox>{error}</ErrorBox>{children}<div className="form-actions">{onCancel&&<button type="button" className="btn secondary" onClick={onCancel}>Cancel</button>}<button className="btn" disabled={busy}>{busy?<><LoaderCircle size={16} className="spin"/>Working…</>:label}</button></div></form>}
export function Field({label,name,type='text',value,required=false,options,children,...rest}){return <label className="field"><span>{label}</span>{options?<select key={String(value)+'-'+options.map(o=>o.value??o).join('|')} name={name} defaultValue={value} {...rest}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:type==='textarea'?<textarea name={name} defaultValue={value} required={required} {...rest}/>:<input name={name} type={type} defaultValue={value} required={required} {...rest}/ >}{children}</label>}
export function Confirm({title,text,onConfirm,onClose}){return <Modal title={title} onClose={onClose}><p className="muted">{text}</p><Form onSubmit={onConfirm} label="Confirm" onCancel={onClose}/></Modal>}

