import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openCheckout,loadCheckout} from '../client/checkout.js';
const order={key:'rzp_test_unit',order_id:'order_unit',amount:100,currency:'INR',test:true};
function harness(){const messages=[];let options,failed,opened=false,verified=false;global.window={Razorpay:class{constructor(o){options=o;}on(name,fn){assert.equal(name,'payment.failed');failed=fn;}open(){opened=true;}}};return {messages,get options(){return options},get failed(){return failed},get opened(){return opened},get verified(){return verified},callbacks:{api:async()=>({success:true}),notify:m=>messages.push(m),onVerified:()=>{verified=true}}};}
test('checkout loads public key and server-created fixed amount without any secret',async()=>{const h=harness();await openCheckout(order,h.callbacks);assert.ok(h.opened);assert.equal(h.options.key,order.key);assert.equal(h.options.amount,100);assert.equal(h.options.order_id,'order_unit');assert.equal(h.options.key_secret,undefined);});
test('checkout forwards all signature fields and only succeeds after backend verification',async()=>{const h=harness();let submitted;h.callbacks.api=async(path,method,data)=>{submitted={path,method,data};return {success:true}};await openCheckout(order,h.callbacks);const details={razorpay_order_id:'order_unit',razorpay_payment_id:'pay_unit',razorpay_signature:'unit-signature'};await h.options.handler(details);assert.deepEqual(submitted.data,details);assert.equal(submitted.path,'/workspace/billing/verify');assert.ok(h.verified);});
test('dismissal, payment failure and verification errors show honest messages',async()=>{const h=harness();h.callbacks.api=async()=>{throw Error('Signature mismatch')};await openCheckout(order,h.callbacks);h.options.modal.ondismiss();h.failed({error:{description:'Payment declined'}});await h.options.handler({});assert.equal(h.verified,false);assert.ok(h.messages.some(m=>m.includes('Checkout closed')));assert.ok(h.messages.some(m=>m.includes('Payment declined')));assert.ok(h.messages.some(m=>m.includes('Signature mismatch')));});
test('checkout script load errors are caught and do not open checkout',async()=>{global.window={};global.document={createElement:()=>({remove(){}}),body:{appendChild(script){queueMicrotask(()=>script.onerror());}}};await assert.rejects(loadCheckout(),/Could not load/);});

