export async function up(k){
await k.schema.createTable('users',t=>{t.uuid('id').primary();t.string('email',190).unique().notNullable();t.string('name').notNullable();t.string('password_hash');t.boolean('verified').defaultTo(false);t.boolean('suspended').defaultTo(false);t.boolean('platform_owner').defaultTo(false);t.string('totp_secret');t.timestamps(true,true);});
await k.schema.createTable('workspaces',t=>{t.uuid('id').primary();t.string('name').notNullable();t.uuid('owner_id').references('users.id').notNullable();t.boolean('trial_used').defaultTo(false);t.string('duplicate_mode').defaultTo('email');t.timestamps(true,true);});
await k.schema.createTable('memberships',t=>{t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('role').notNullable();t.primary(['workspace_id','user_id']);});
await k.schema.createTable('sessions',t=>{t.string('hash',64).primary();t.uuid('user_id').references('users.id');t.string('csrf',64);t.timestamp('expires_at').notNullable().index();t.timestamp('mfa_at');t.timestamps(true,true);});
await k.schema.createTable('auth_identities',t=>{t.increments('id');t.uuid('user_id').references('users.id');t.string('provider');t.string('subject');t.unique(['provider','subject']);});
await k.schema.createTable('auth_tokens',t=>{t.string('hash',64).primary();t.uuid('user_id').references('users.id');t.string('kind');t.timestamp('expires_at');t.timestamp('used_at');t.timestamps(true,true);});
await k.schema.createTable('invitations',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.string('email',190);t.string('role');t.string('token_hash',64).unique();t.timestamp('expires_at');t.timestamp('used_at');t.timestamp('revoked_at');t.timestamps(true,true);t.index(['workspace_id','email']);});
await k.schema.createTable('plans',t=>{t.string('id',30).primary();t.string('name');t.integer('price_paise').unsigned();t.json('limits');t.integer('version').defaultTo(1);t.timestamps(true,true);});
await k.schema.createTable('entitlements',t=>{t.uuid('workspace_id').primary().references('workspaces.id');t.json('overrides');t.timestamp('updated_at').defaultTo(k.fn.now());});
await k.schema.createTable('subscriptions',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.string('plan_id',30).references('plans.id');t.string('kind');t.string('status');t.timestamp('starts_at');t.timestamp('ends_at');t.boolean('cancel_at_end').defaultTo(false);t.json('snapshot');t.uuid('payment_id').unique();t.timestamps(true,true);t.index(['workspace_id','starts_at','ends_at']);});
await k.schema.createTable('payment_orders',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.string('provider');t.string('provider_order_id').unique();t.string('merchant_id');t.string('plan_id',30);t.integer('amount_paise').unsigned();t.string('currency',3);t.string('status');t.json('snapshot');t.timestamp('expires_at');t.timestamps(true,true);t.index(['workspace_id','status']);});
await k.schema.createTable('payments',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('order_id').unique().references('payment_orders.id');t.string('provider_payment_id').unique();t.integer('amount_paise').unsigned();t.string('currency',3);t.string('status');t.string('provider');t.timestamp('paid_at');t.timestamps(true,true);});
await k.schema.createTable('webhook_events',t=>{t.string('id',190).primary();t.string('provider');t.string('event');t.string('payload_hash',64);t.timestamp('processed_at');});
for(const table of ['companies','contacts','leads','deals','tasks','notes']){
await k.schema.createTable(table,t=>{t.uuid('id').primary();t.uuid('workspace_id').notNullable().references('workspaces.id');t.string('name').notNullable();t.uuid('assigned_to').notNullable();t.foreign(['workspace_id','assigned_to']).references(['workspace_id','user_id']).inTable('memberships');t.string('email',190);t.string('phone',60);t.string('company');t.string('source');t.string('status').defaultTo(table==='tasks'?'Open':'New');t.bigInteger('value_paise').unsigned().defaultTo(0);t.string('currency',3).defaultTo('INR');t.string('tags');t.text('notes');t.timestamp('follow_up_at');t.timestamp('due_at');t.string('priority').defaultTo('Normal');t.string('linked_type');t.uuid('linked_id');t.uuid('pipeline_id');t.boolean('archived').defaultTo(false);t.timestamps(true,true);t.unique(['workspace_id','id']);t.index(['workspace_id','archived','assigned_to']);t.index(['workspace_id','email']);});
}
await k.schema.createTable('pipelines',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.string('name');t.timestamps(true,true);t.unique(['workspace_id','id']);});
await k.schema.createTable('pipeline_stages',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('pipeline_id');t.foreign(['workspace_id','pipeline_id']).references(['workspace_id','id']).inTable('pipelines');t.string('name');t.integer('position');t.string('kind').defaultTo('open');t.unique(['pipeline_id','name']);});
await k.schema.createTable('activities',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('record_type');t.uuid('record_id');t.string('description');t.timestamp('created_at').defaultTo(k.fn.now());t.index(['workspace_id','created_at']);});
await k.schema.createTable('reminders',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.uuid('task_id').references('tasks.id');t.timestamp('due_at');t.timestamp('sent_at');t.boolean('email').defaultTo(false);t.unique(['task_id','due_at']);});
await k.schema.createTable('usage_counters',t=>{t.uuid('workspace_id').references('workspaces.id');t.string('period',80);t.string('metric',30);t.integer('used').unsigned().defaultTo(0);t.primary(['workspace_id','period','metric']);});
await k.schema.createTable('crm_invoices',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('created_by').references('users.id');t.string('number');t.string('client_name');t.string('client_email');t.string('currency',3);t.integer('tax_bps').unsigned();t.bigInteger('subtotal_paise').unsigned();t.bigInteger('total_paise').unsigned();t.string('status').defaultTo('Unpaid');t.date('due_date');t.text('memo');t.timestamps(true,true);t.unique(['workspace_id','number']);});
await k.schema.createTable('invoice_items',t=>{t.uuid('id').primary();t.uuid('invoice_id').references('crm_invoices.id');t.string('description');t.integer('quantity').unsigned();t.integer('unit_paise').unsigned();});
await k.schema.createTable('billing_receipts',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('payment_id').unique().references('payments.id');t.string('number').unique();t.json('details');t.timestamp('created_at').defaultTo(k.fn.now());});
await k.schema.createTable('email_drafts',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('recipient',190);t.string('subject');t.text('body');t.boolean('is_template').defaultTo(false);t.timestamps(true,true);});
await k.schema.createTable('email_jobs',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.uuid('draft_id').unique().references('email_drafts.id');t.string('status');t.string('message_id').unique();t.text('error');t.timestamps(true,true);});
await k.schema.createTable('notifications',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('title');t.text('body');t.boolean('read').defaultTo(false);t.timestamps(true,true);t.index(['workspace_id','user_id']);});
await k.schema.createTable('ai_conversations',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('action');t.text('prompt');t.text('response');t.string('mode');t.integer('tokens');t.timestamps(true,true);});
await k.schema.createTable('support_tickets',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('user_id').references('users.id');t.string('email');t.string('subject');t.text('message');t.string('status').defaultTo('Open');t.text('reply');t.timestamps(true,true);});
await k.schema.createTable('audit_logs',t=>{t.uuid('id').primary();t.uuid('workspace_id').references('workspaces.id');t.uuid('actor_id').references('users.id');t.string('action');t.string('target');t.text('reason');t.timestamp('created_at').defaultTo(k.fn.now());t.index(['workspace_id','created_at']);});
}
export async function down(){throw Error('Automatic destructive rollback is disabled. Restore a verified backup instead.');}

