import {Router} from 'express';
import {z} from 'zod';
import {parse} from 'csv-parse/sync';
import {db,json} from './db.js';
import {id,fail,visible,manage,audit} from './security.js';
import {lockWorkspace,entitlement,date} from './plans.js';
export const router=Router();
export const types=['leads','contacts','companies','deals','tasks','notes'];
const record=z.object({name:z.string().trim().min(1).max(150),email:z.union([z.string().email().max(190),z.literal('')]).optional().default(''),phone:z.string().max(60).optional().default(''),company:z.string().max(150).optional().default(''),source:z.string().max(60).optional().default(''),status:z.string().max(60).optional().default('New'),assigned_to:z.string().uuid().optional(),value_paise:z.coerce.number().int().min(0).max(1e12).optional().default(0),currency:z.enum(['INR','USD','EUR','GBP']).default('INR'),tags:z.string().max(255).optional().default(''),notes:z.string().max(10000).optional().default(''),follow_up_at:z.string().datetime().nullable().optional(),due_at:z.string().datetime().nullable().optional(),priority:z.enum(['Low','Normal','High','Urgent']).default('Normal'),linked_type:z.enum(['leads','contacts','companies','deals']).nullable().optional(),linked_id:z.string().uuid().nullable().optional(),pipeline_id:z.string().uuid().nullable().optional(),archived:z.boolean().optional().default(false)});
function type(req){if(!types.includes(req.params.type))fail('Unknown record type',404);return req.params.type;}
export async function validateRecord(k,req,table,body,exclude){
const b=record.parse(body);b.assigned_to=b.assigned_to||req.user.id;if(req.role==='member'&&b.assigned_to!==req.user.id)fail('Members can assign only to themselves',403);
if(!await k('memberships').where({workspace_id:req.w,user_id:b.assigned_to}).first())fail('Assignee is not in this workspace');
if(b.linked_id){if(!b.linked_type||!await visible(k(b.linked_type),req).where({id:b.linked_id}).first())fail('Linked record not found',404);}
if(['leads','deals'].includes(table)){const pipeline=b.pipeline_id?await k('pipelines').where({workspace_id:req.w,id:b.pipeline_id}).first():await k('pipelines').where({workspace_id:req.w}).first();if(!pipeline)fail('Pipeline not found');b.pipeline_id=pipeline.id;if(!await k('pipeline_stages').where({workspace_id:req.w,pipeline_id:pipeline.id,name:b.status}).first())fail('Invalid pipeline stage');}
const ws=await k('workspaces').where({id:req.w}).first();const field=ws.duplicate_mode==='email'?'email':ws.duplicate_mode==='phone'?'phone':null;
if(field&&b[field]&&['leads','contacts','companies'].includes(table)){const q=k(table).where({workspace_id:req.w,[field]:b[field],archived:false});if(exclude)q.whereNot({id:exclude});if(await q.first())fail('Duplicate '+field+' already exists',409);}
for(const key of ['follow_up_at','due_at'])if(b[key])b[key]=new Date(b[key]);
return b;
}
async function log(k,req,table,rid,text){await k('activities').insert({id:id(),workspace_id:req.w,user_id:req.user.id,record_type:table,record_id:rid,description:text});}
async function limitRecords(k,req,table,n){if(!['leads','contacts'].includes(table))return;const e=await entitlement(k,req.w);const [{n:used}]=await k(table).where({workspace_id:req.w,archived:false}).count('* as n');if(Number(used)+n>e.limits[table])fail('Your '+table+' limit is reached. Archive records or upgrade.',403);}
router.get('/dashboard',async(req,res)=>{
const tier=await entitlement(db,req.w);if(tier.limits.dashboard==='Basic'&&(req.query.from||req.query.to))fail('Date filters require Basic or above',403);const range=z.object({from:z.string().date().optional(),to:z.string().date().optional()}).parse(req.query);
const scoped=(table)=>{const q=visible(db(table),req).where({archived:false});if(range.from)q.where('created_at','>=',range.from);if(range.to)q.where('created_at','<',new Date(new Date(range.to).getTime()+86400000));return q;};
const [leads,contacts,deals,tasks]=await Promise.all(['leads','contacts','deals','tasks'].map(scoped));
const stages=await db('pipeline_stages').where({workspace_id:req.w}).orderBy('position');const kind=(r)=>stages.find(s=>s.pipeline_id===r.pipeline_id&&s.name===r.status)?.kind||'open';
const won=leads.filter(x=>kind(x)==='won').length;const open=deals.filter(x=>kind(x)==='open');const currencies={};for(const d of deals){const c=currencies[d.currency]||{pipeline:0,won:0};if(kind(d)==='open')c.pipeline+=Number(d.value_paise);if(kind(d)==='won')c.won+=Number(d.value_paise);currencies[d.currency]=c;}
const activityQ=db('activities').where({workspace_id:req.w}).orderBy('created_at','desc').limit(12);if(req.role==='member')activityQ.where({user_id:req.user.id});
const trend={};for(const l of leads){const month=String(l.created_at).slice(0,10);trend[month]=(trend[month]||0)+1;}
res.json({dashboardLevel:tier.limits.dashboard,sourceBreakdown:tier.limits.dashboard==='Advanced'?Object.entries(leads.reduce((acc,l)=>{acc[l.source||'Other']=(acc[l.source||'Other']||0)+1;return acc;},{})).map(([source,count])=>({source,count})):[],totalLeads:leads.length,totalContacts:contacts.length,openDeals:open.length,currencies,conversion:leads.length?Math.round(won/leads.length*100):0,overdue:tasks.filter(t=>t.status!=='Completed'&&t.due_at&&date(t.due_at)<new Date()).length,followups:leads.filter(l=>l.follow_up_at).sort((a,b)=>a.follow_up_at.localeCompare(b.follow_up_at)).slice(0,6),activities:await activityQ,stages:stages.map(s=>({name:s.name,pipeline_id:s.pipeline_id,count:leads.filter(l=>l.status===s.name&&l.pipeline_id===s.pipeline_id).length})),trend:Object.entries(trend).sort().map(([month,leads],i,all)=>({month,leads:all.slice(0,i+1).reduce((sum,x)=>sum+x[1],0)}))});
});
router.get('/search',async(req,res)=>{const q=String(req.query.q||'').slice(0,100);const results=[];if(q.length>1)for(const table of types){const rows=await visible(db(table),req).where({archived:false}).where(b=>b.where('name','like','%'+q+'%').orWhere('company','like','%'+q+'%').orWhere('email','like','%'+q+'%')).limit(8);results.push(...rows.map(r=>({id:r.id,name:r.name,type:table,company:r.company})));}res.json(results);});
router.get('/pipelines',async(req,res)=>res.json({pipelines:await db('pipelines').where({workspace_id:req.w}),stages:await db('pipeline_stages').where({workspace_id:req.w}).orderBy('position')}));
router.post('/pipelines',async(req,res)=>{manage(req);const b=z.object({name:z.string().min(1).max(100),stages:z.array(z.object({name:z.string().min(1).max(60),kind:z.enum(['open','won','lost'])})).min(3).max(12)}).parse(req.body);if(new Set(b.stages.map(s=>s.name)).size!==b.stages.length||!b.stages.some(s=>s.kind==='won')||!b.stages.some(s=>s.kind==='lost'))fail('Use unique stages including Won and Lost outcomes');await db.transaction(async k=>{await lockWorkspace(k,req.w);const e=await entitlement(k,req.w);if(!e.limits.custom_pipeline)fail('Custom pipelines require Pro or Business',403);const [{n}]=await k('pipelines').where({workspace_id:req.w}).count('* as n');if(n>=e.limits.pipelines)fail('Pipeline limit reached',403);const pid=id();await k('pipelines').insert({id:pid,workspace_id:req.w,name:b.name});await k('pipeline_stages').insert(b.stages.map((s,position)=>({...s,id:id(),workspace_id:req.w,pipeline_id:pid,position})));await audit(k,req,'pipeline.create',pid);});res.status(201).json({ok:true});});
router.get('/records/:type/export',async(req,res)=>{const table=type(req);const rows=await visible(db(table),req).where({archived:req.query.archived==='true'}).orderBy('created_at');const cols=['name','email','phone','company','source','status','value_paise','currency','tags','notes','follow_up_at','due_at','priority'];const cell=x=>{let s=String(x??'');if(/^[\s]*[=+@-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};res.set('Content-Type','text/csv; charset=utf-8').attachment('leadnest-'+table+'.csv').send('\uFEFF'+[cols.join(','),...rows.map(r=>cols.map(c=>cell(r[c])).join(','))].join('\r\n'));});
router.post('/records/:type/import',async(req,res)=>{const table=type(req);if(!['leads','contacts','companies'].includes(table))fail('Import supports leads, contacts and companies');const b=z.object({csv:z.string().max(1000000),mapping:z.record(z.string(),z.string()),duplicate:z.enum(['skip','error']).default('skip'),commit:z.boolean().default(false)}).parse(req.body);let rows;try{rows=parse(b.csv,{columns:true,skip_empty_lines:true,bom:true,max_record_size:20000});}catch{fail('CSV could not be parsed. Check quoted fields and column counts.');}if(rows.length>2000)fail('Import up to 2,000 rows at a time');const result={valid:[],errors:[],skipped:0};await db.transaction(async k=>{await lockWorkspace(k,req.w);const e=await entitlement(k,req.w);if(!e.limits.import)fail('CSV import requires Basic or above',403);const ws=await k('workspaces').where({id:req.w}).first();const seen=new Set();for(const [i,r] of rows.entries()){try{const mapped={};for(const [dest,src] of Object.entries(b.mapping))if(r[src]!==undefined&&r[src]!=='')mapped[dest]=r[src];if(mapped.follow_up_at)mapped.follow_up_at=new Date(mapped.follow_up_at).toISOString();const v=await validateRecord(k,req,table,mapped);const dupKey=ws.duplicate_mode==='off'?null:v[ws.duplicate_mode];if(dupKey&&seen.has(dupKey))fail('Duplicate in this CSV',409);if(dupKey)seen.add(dupKey);result.valid.push(v);}catch(e){if(e.status===409&&b.duplicate==='skip')result.skipped++;else result.errors.push({row:i+2,error:e.issues?.[0]?.message||e.message});}}await limitRecords(k,req,table,result.valid.length);if(b.commit){if(result.errors.length)fail('Resolve row errors before importing');for(const row of result.valid){const rid=id();await k(table).insert({...row,id:rid,workspace_id:req.w});await log(k,req,table,rid,'Imported '+row.name);}await audit(k,req,'csv.import',table,String(result.valid.length)+' records');}});res.json({preview:result.valid.slice(0,20),valid:result.valid.length,errors:result.errors,skipped:result.skipped,committed:b.commit});});
router.get('/records/:type',async(req,res)=>{const table=type(req);const b=z.object({q:z.string().max(100).optional(),status:z.string().max(60).optional(),page:z.coerce.number().int().min(1).default(1),sort:z.enum(['name','created_at','updated_at','value_paise','due_at']).default('created_at'),direction:z.enum(['asc','desc']).default('desc'),archived:z.enum(['true','false']).default('false'),pipeline:z.string().uuid().optional()}).parse(req.query);const q=visible(db(table),req).where({archived:b.archived==='true'});if(b.q)q.where(x=>x.where('name','like','%'+b.q+'%').orWhere('company','like','%'+b.q+'%').orWhere('email','like','%'+b.q+'%'));if(b.status)q.where({status:b.status});if(b.pipeline)q.where({pipeline_id:b.pipeline});const [{n}]=await q.clone().count('* as n');const rows=await q.orderBy(b.sort,b.direction).limit(25).offset((b.page-1)*25);res.json({rows,total:Number(n),page:b.page,pages:Math.max(1,Math.ceil(n/25))});});
router.get('/records/:type/:id',async(req,res)=>{const row=await visible(db(type(req)),req).where({id:req.params.id}).first();if(!row)fail('Record not found',404);res.json(row);});
router.post('/records/:type',async(req,res)=>{const table=type(req);let rid;await db.transaction(async k=>{await lockWorkspace(k,req.w);const b=await validateRecord(k,req,table,req.body);await limitRecords(k,req,table,1);rid=id();await k(table).insert({...b,id:rid,workspace_id:req.w});await log(k,req,table,rid,'Created '+b.name);if(table==='leads'&&b.follow_up_at)await k('reminders').insert({id:id(),workspace_id:req.w,user_id:b.assigned_to,lead_id:rid,due_at:b.follow_up_at,email:true});if(table==='tasks'&&b.due_at)await k('reminders').insert({id:id(),workspace_id:req.w,user_id:b.assigned_to,task_id:rid,due_at:b.due_at,email:true});});res.status(201).json({id:rid});});
router.patch('/records/:type/:id',async(req,res)=>{const table=type(req);await db.transaction(async k=>{await lockWorkspace(k,req.w);const old=await visible(k(table),req).where({id:req.params.id}).first();if(!old)fail('Record not found',404);const merged={...old,...req.body};for(const key of ['follow_up_at','due_at'])if(merged[key])merged[key]=new Date(merged[key]).toISOString();merged.archived=!!merged.archived;const b=await validateRecord(k,req,table,merged,old.id);if(old.archived&&!b.archived)await limitRecords(k,req,table,1);await k(table).where({id:old.id,workspace_id:req.w}).update({...b,updated_at:new Date()});await log(k,req,table,old.id,b.archived?'Archived '+b.name:old.status!==b.status?b.name+' moved to '+b.status:'Updated '+b.name);if(table==='leads'){await k('reminders').where({lead_id:old.id,workspace_id:req.w}).del();if(b.follow_up_at&&!b.archived&&!['Won','Lost'].includes(b.status))await k('reminders').insert({id:id(),workspace_id:req.w,user_id:b.assigned_to,lead_id:old.id,due_at:b.follow_up_at,email:true});}if(table==='tasks'){await k('reminders').where({task_id:old.id,workspace_id:req.w}).del();if(b.due_at&&!b.archived&&b.status!=='Completed')await k('reminders').insert({id:id(),workspace_id:req.w,user_id:b.assigned_to,task_id:old.id,due_at:b.due_at,email:true});}});res.json({ok:true});});

