import {Router} from 'express';
import {z} from 'zod';
import {db,json} from './db.js';
import {fail,audit} from './security.js';
import {entitlement,lockWorkspace,date} from './plans.js';
export const router=Router();
router.use((req,res,next)=>{if(!req.user.platform_owner)return next(Object.assign(Error('Platform owner access required'),{status:403}));if(!req.session.mfa_at||Date.now()-date(req.session.mfa_at).getTime()>15*60000)return next(Object.assign(Error('Verify your authenticator code to open the owner area'),{status:428}));next();});
router.get('/overview',async(req,res)=>{const search=String(req.query.q||'').slice(0,100);const customers=await db('workspaces').join('users','users.id','workspaces.owner_id').where(q=>q.where('workspaces.name','like','%'+search+'%').orWhere('users.email','like','%'+search+'%')).select('workspaces.id','workspaces.name','workspaces.trial_used','users.email','users.suspended','users.id as owner_id').limit(100);for(const c of customers){c.entitlement=await entitlement(db,c.id);c.usage=await db('usage_counters').where({workspace_id:c.id,period:c.entitlement.period});}const payments=await db('payments').orderBy('created_at','desc').limit(100);const revenue=await db('payments').where({status:'captured',provider:'razorpay',is_test:false}).sum('amount_paise as value').first();const pending=await db('payment_orders').where({status:'pending'}).sum('amount_paise as value').first();res.json({customers,payments,revenue:Number(revenue.value||0),pending:Number(pending.value||0),plans:(await db('plans')).map(p=>({...p,limits:json(p.limits)})),tickets:await db('support_tickets').orderBy('created_at','desc').limit(100),audit:await db('audit_logs').whereNull('workspace_id').orderBy('created_at','desc').limit(100)});});
router.post('/accounts/:id',async(req,res)=>{const b=z.object({suspended:z.boolean(),reason:z.string().min(5).max(1000),confirm:z.literal(true)}).parse(req.body);if(req.params.id===req.user.id)fail('You cannot suspend your own account');await db.transaction(async k=>{const u=await k('users').where({id:req.params.id}).first();if(!u||u.platform_owner)fail('Account unavailable');await k('users').where({id:u.id}).update({suspended:b.suspended});if(b.suspended)await k('sessions').where({user_id:u.id}).del();await audit(k,req,b.suspended?'platform.suspend':'platform.restore',u.id,b.reason);});res.json({ok:true});});
router.post('/subscriptions/:workspace',async(req,res)=>{const b=z.object({action:z.enum(['cancel','revoke']),reason:z.string().min(5).max(1000),confirm:z.literal(true)}).parse(req.body);await db.transaction(async k=>{await lockWorkspace(k,req.params.workspace);const q=k('subscriptions').where({workspace_id:req.params.workspace,status:'active'}).where('ends_at','>',new Date());await q.update(b.action==='cancel'?{cancel_at_end:true}:{status:'revoked'});await audit(k,req,'platform.subscription.'+b.action,req.params.workspace,b.reason);});res.json({message:'Access updated. No refund has been issued.'});});
router.patch('/plans/:id',async(req,res)=>{const b=z.object({price_paise:z.number().int().min(0).max(100000000),limits:z.object({seats:z.number().int().min(1).max(100000),leads:z.number().int().min(0).max(10000000),contacts:z.number().int().min(0).max(10000000),pipelines:z.number().int().min(1).max(100),emails:z.number().int().min(0).max(1000000),invoices:z.number().int().min(0).max(1000000),ai:z.number().int().min(0).max(100000),import:z.boolean(),custom_pipeline:z.boolean(),audit:z.boolean(),dashboard:z.enum(['Basic','Standard','Advanced'])})}).parse(req.body);if(req.params.id==='free'&&b.price_paise!==0)fail('Free must remain free');await db.transaction(async k=>{const p=await k('plans').where({id:req.params.id}).forUpdate().first();if(!p)fail('Plan not found');await k('plans').where({id:p.id}).update({price_paise:b.price_paise,limits:JSON.stringify(b.limits),version:p.version+1});await audit(k,req,'platform.plan-update',p.id,'Future purchases only');});res.json({ok:true});});
router.patch('/support/:id',async(req,res)=>{const b=z.object({status:z.enum(['Open','In progress','Resolved']),reply:z.string().max(5000)}).parse(req.body);await db('support_tickets').where({id:req.params.id}).update(b);await audit(db,req,'platform.support',req.params.id);res.json({ok:true});});


