import {Router} from 'express';
import {z} from 'zod';
import {db,json} from './db.js';
import {id,token,hash,fail,manage,owner,audit,visible} from './security.js';
import {lockWorkspace,entitlement,quota} from './plans.js';
import {sendMail,mailConfigured} from './mail.js';
import PDFDocument from 'pdfkit';
export const router=Router();
router.get('/team',async(req,res)=>{res.json({members:await db('memberships').join('users','users.id','memberships.user_id').where({workspace_id:req.w}).select('users.id','users.name','users.email','memberships.role'),invitations:req.role==='member'?[]:await db('invitations').where({workspace_id:req.w,used_at:null,revoked_at:null}).where('expires_at','>',new Date()).select('id','email','role','expires_at')});});
router.post('/team/invite',async(req,res)=>{manage(req);const b=z.object({email:z.string().email().max(190).transform(s=>s.toLowerCase()),role:z.enum(['admin','member'])}).parse(req.body);if(req.role==='admin'&&b.role==='admin')fail('Only the owner may invite an admin',403);const raw=token();await db.transaction(async k=>{await lockWorkspace(k,req.w);const e=await entitlement(k,req.w);const [{n:seats}]=await k('memberships').where({workspace_id:req.w}).count('* as n');const [{n:pending}]=await k('invitations').where({workspace_id:req.w,used_at:null,revoked_at:null}).where('expires_at','>',new Date()).count('* as n');if(Number(seats)+Number(pending)>=e.limits.seats)fail('Seat limit reached, including pending invitations',403);await k('invitations').insert({id:id(),workspace_id:req.w,email:b.email,role:b.role,token_hash:hash(raw),expires_at:new Date(Date.now()+72*3600000)});await audit(k,req,'team.invite',b.email);});await sendMail({to:b.email,subject:'Join your team on LeadNest',text:'Sign in or create an account using '+b.email+', then open '+process.env.APP_URL+'/app/team?invite='+raw});res.json({message:'Invitation sent. It expires in 72 hours.'});});
router.post('/team/accept',async(req,res)=>{const b=z.object({token:z.string().length(64)}).parse(req.body);let w;await db.transaction(async k=>{const candidate=await k('invitations').where({token_hash:hash(b.token)}).first();if(!candidate)fail('Invitation not found');await lockWorkspace(k,candidate.workspace_id);const inv=await k('invitations').where({id:candidate.id,used_at:null,revoked_at:null}).where('expires_at','>',new Date()).forUpdate().first();if(!inv||inv.email!==req.user.email)fail('Invitation is expired, used, or addressed to another account');if(await k('memberships').where({workspace_id:inv.workspace_id,user_id:req.user.id}).first())fail('Already a member');const e=await entitlement(k,inv.workspace_id);const [{n}]=await k('memberships').where({workspace_id:inv.workspace_id}).count('* as n');if(n>=e.limits.seats)fail('Workspace seat limit reached',403);await k('memberships').insert({workspace_id:inv.workspace_id,user_id:req.user.id,role:inv.role});await k('invitations').where({id:inv.id}).update({used_at:new Date()});w=inv.workspace_id;await audit(k,{...req,w},'team.join',req.user.id);});res.json({workspace_id:w});});
router.delete('/team/invitations/:id',async(req,res)=>{manage(req);await db('invitations').where({id:req.params.id,workspace_id:req.w}).update({revoked_at:new Date()});res.json({ok:true});});
router.patch('/team/:id',async(req,res)=>{owner(req);const b=z.object({role:z.enum(['admin','member'])}).parse(req.body);const count=await db('memberships').where({workspace_id:req.w,user_id:req.params.id}).whereNot({role:'owner'}).update(b);if(!count)fail('Member not found',404);await audit(db,req,'team.role',req.params.id,b.role);res.json({ok:true});});
router.delete('/team/:id',async(req,res)=>{manage(req);await db.transaction(async k=>{const ws=await lockWorkspace(k,req.w);const m=await k('memberships').where({workspace_id:req.w,user_id:req.params.id}).first();if(!m||m.role==='owner'||req.role==='admin'&&m.role==='admin')fail('Cannot remove this member',403);for(const t of ['leads','contacts','companies','deals','tasks','notes'])await k(t).where({workspace_id:req.w,assigned_to:m.user_id}).update({assigned_to:ws.owner_id});await k('reminders').where({workspace_id:req.w,user_id:m.user_id}).update({user_id:ws.owner_id});await k('memberships').where({workspace_id:req.w,user_id:m.user_id}).del();await audit(k,req,'team.remove',m.user_id);});res.json({ok:true});});
router.get('/settings',async(req,res)=>res.json(await db('workspaces').where({id:req.w}).select('name','duplicate_mode').first()));
router.patch('/settings',async(req,res)=>{owner(req);const b=z.object({name:z.string().min(2).max(100),duplicate_mode:z.enum(['off','email','phone'])}).parse(req.body);await db('workspaces').where({id:req.w}).update(b);await audit(db,req,'workspace.settings',req.w);res.json({ok:true});});
router.get('/audit',async(req,res)=>{manage(req);if(!(await entitlement(db,req.w)).limits.audit)fail('Team audit history requires Business',403);res.json(await db('audit_logs').where({workspace_id:req.w}).orderBy('created_at','desc').limit(200));});
router.get('/notifications',async(req,res)=>res.json(await db('notifications').where({workspace_id:req.w,user_id:req.user.id}).orderBy('created_at','desc').limit(50)));
router.post('/notifications/read',async(req,res)=>{await db('notifications').where({workspace_id:req.w,user_id:req.user.id}).update({read:true});res.json({ok:true});});
router.get('/emails',async(req,res)=>{const q=db('email_drafts').where({workspace_id:req.w});if(req.role==='member')q.where({user_id:req.user.id});const drafts=await q.orderBy('created_at','desc').limit(100);const jobs=await db('email_jobs').where({workspace_id:req.w}).whereIn('draft_id',drafts.map(d=>d.id));res.json({drafts,jobs,configured:mailConfigured()});});
const draftSchema=z.object({recipient:z.union([z.string().email().max(190),z.literal('')]),subject:z.string().min(1).max(190),body:z.string().min(1).max(20000),is_template:z.boolean().default(false)});
router.post('/emails',async(req,res)=>{const b=draftSchema.parse(req.body);const rid=id();await db('email_drafts').insert({...b,id:rid,workspace_id:req.w,user_id:req.user.id});res.status(201).json({id:rid});});
router.patch('/emails/:id',async(req,res)=>{const b=draftSchema.parse(req.body);await db.transaction(async k=>{await lockWorkspace(k,req.w);const q=k('email_drafts').where({id:req.params.id,workspace_id:req.w});if(req.role==='member')q.where({user_id:req.user.id});if(!await q.first())fail('Draft not found',404);if(await k('email_jobs').where({draft_id:req.params.id}).first())fail('Create a new draft to send another email');await q.update({...b,updated_at:new Date()});});res.json({ok:true});});
router.post('/emails/:id/send',async(req,res)=>{if(req.body.confirm!==true)fail('Confirm sending this email');if(!mailConfigured())fail('Email sending is awaiting provider configuration',503);await db.transaction(async k=>{await lockWorkspace(k,req.w);const q=k('email_drafts').where({id:req.params.id,workspace_id:req.w});if(req.role==='member')q.where({user_id:req.user.id});const d=await q.first();if(!d||!d.recipient||d.is_template)fail('Choose a complete email draft');const existing=await k('email_jobs').where({draft_id:d.id}).first();if(existing)return;await quota(k,req.w,'emails');const job=id();await k('email_jobs').insert({id:job,workspace_id:req.w,user_id:req.user.id,draft_id:d.id,status:'queued',message_id:'<'+job+'@leadnest.local>'});await audit(k,req,'email.queue',d.id);});res.json({message:'Email queued. Delivery status will appear here.'});});
router.get('/invoices',async(req,res)=>{const q=db('crm_invoices').where({workspace_id:req.w});if(req.role==='member')q.where({created_by:req.user.id});res.json(await q.orderBy('created_at','desc').limit(100));});
router.post('/invoices',async(req,res)=>{const b=z.object({client_name:z.string().min(1).max(150),client_email:z.union([z.string().email(),z.literal('')]).default(''),currency:z.enum(['INR','USD','EUR','GBP']).default('INR'),tax_bps:z.coerce.number().int().min(0).max(10000).default(0),due_date:z.string().date(),memo:z.string().max(2000).default(''),items:z.array(z.object({description:z.string().min(1).max(190),quantity:z.coerce.number().int().min(1).max(100000),unit_paise:z.coerce.number().int().min(0).max(100000000)})).min(1).max(50)}).parse(req.body);let rid;await db.transaction(async k=>{await lockWorkspace(k,req.w);await quota(k,req.w,'invoices');rid=id();const sub=b.items.reduce((s,i)=>s+i.quantity*i.unit_paise,0);if(sub>1e12)fail('Invoice total exceeds the supported amount');const {items,...data}=b;await k('crm_invoices').insert({...data,id:rid,workspace_id:req.w,created_by:req.user.id,number:'INV-'+rid.slice(0,8).toUpperCase(),subtotal_paise:sub,total_paise:sub+Math.round(sub*b.tax_bps/10000)});await k('invoice_items').insert(items.map(i=>({...i,id:id(),invoice_id:rid})));await audit(k,req,'invoice.create',rid);});res.status(201).json({id:rid});});
async function invoice(req){const q=db('crm_invoices').where({workspace_id:req.w,id:req.params.id});if(req.role==='member')q.where({created_by:req.user.id});const inv=await q.first();if(!inv)fail('Invoice not found',404);return inv;}
router.patch('/invoices/:id',async(req,res)=>{const b=z.object({status:z.enum(['Unpaid','Paid','Void'])}).parse(req.body);await invoice(req);await db('crm_invoices').where({id:req.params.id,workspace_id:req.w}).update(b);await audit(db,req,'invoice.status',req.params.id,b.status);res.json({ok:true});});
function pdf(res,name,title,lines){res.set('Content-Type','application/pdf').attachment(name);const doc=new PDFDocument({margin:50});doc.pipe(res);doc.fontSize(26).fillColor('#123253').text(title);doc.moveDown().fontSize(10).fillColor('#333333');for(const line of lines)doc.text(line,{lineGap:8});doc.end();}
router.get('/invoices/:id/pdf',async(req,res)=>{const i=await invoice(req);const ws=await db('workspaces').where({id:req.w}).first();const items=await db('invoice_items').where({invoice_id:i.id});pdf(res,i.number+'.pdf',ws.name+' | Invoice',[i.number,'Bill to: '+i.client_name+' '+i.client_email,'Due: '+i.due_date,'Status: '+i.status,...items.map(x=>x.description+' | '+x.quantity+' x '+i.currency+' '+(x.unit_paise/100).toFixed(2)), 'Subtotal: '+i.currency+' '+(i.subtotal_paise/100).toFixed(2),'Tax: '+(i.tax_bps/100)+'%','Total: '+i.currency+' '+(i.total_paise/100).toFixed(2),i.memo||'','Client payments are arranged directly with '+ws.name+'.']);});
router.get('/billing/receipts/:id/pdf',async(req,res)=>{owner(req);const r=await db('billing_receipts').where({id:req.params.id,workspace_id:req.w}).first();if(!r)fail('Receipt not found',404);const d=json(r.details);pdf(res,r.number+'.pdf','LeadNest subscription receipt',[d.test?'TEST PAYMENT - no money collected':'Payment received',r.number,'Plan: '+d.plan,'Amount: INR '+(d.amount_paise/100).toFixed(2),'From: '+d.starts_at,'Until: '+d.ends_at,'Cancellation does not automatically refund this payment.']);});
router.get('/support',async(req,res)=>{const q=db('support_tickets').where({workspace_id:req.w});if(req.role==='member')q.where({user_id:req.user.id});res.json(await q.orderBy('created_at','desc').limit(100));});
router.post('/support',async(req,res)=>{const b=z.object({subject:z.string().min(3).max(150),message:z.string().min(5).max(5000)}).parse(req.body);await db('support_tickets').insert({...b,id:id(),workspace_id:req.w,user_id:req.user.id,email:req.user.email});res.status(201).json({message:'Ticket created. Our team will review it.'});});

