import {chromium} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const results=[];const leadName='Browser QA '+Date.now();
try{
await mkdir('screenshots',{recursive:true});
await page.goto('http://127.0.0.1:3000');await page.getByRole('heading',{name:/Less busywork/}).waitFor();await page.screenshot({path:'screenshots/home-desktop.png',fullPage:true});results.push('Home page rendered');
const credentials=await readFile('DEVELOPMENT-ACCESS.txt','utf8');const password=credentials.match(/Password: (.+)/)[1].trim();
await page.goto('http://127.0.0.1:3000/login');await page.getByLabel('Email address',{exact:true}).fill('demo@leadnest.local');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:/Welcome back, Alex/}).waitFor();await page.getByText('Total leads',{exact:true}).waitFor();await page.screenshot({path:'screenshots/dashboard-desktop.png',fullPage:true});results.push('Login and database dashboard rendered');
await page.getByRole('button',{name:'Add lead',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByLabel('Name',{exact:true}).fill(leadName);await page.getByLabel('Email',{exact:true}).fill('browser-qa-'+Date.now()+'@example.test');await page.getByRole('button',{name:'Create lead',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});results.push('Lead creation modal saved');
await page.goto('http://127.0.0.1:3000/app/leads');await page.getByLabel('Search leads').fill(leadName);await page.locator('.name-button').filter({hasText:leadName}).first().waitFor();await page.reload();await page.getByLabel('Search leads').fill(leadName);await page.locator('.name-button').filter({hasText:leadName}).first().click();await page.locator('select[name=status]').selectOption('Qualified');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByText('Qualified',{exact:true}).first().waitFor();results.push('Lead persisted after reload and stage edit saved');
await page.getByRole('button',{name:'Archive '+leadName,exact:true}).first().click();await page.getByRole('heading',{name:'No matching records'}).waitFor();results.push('Archive hides active record without deleting');
for(const route of ['contacts','companies','deals','tasks','notes','pipeline','team','email','invoices','billing','settings','ai','support']){await page.goto('http://127.0.0.1:3000/app/'+route);await page.waitForLoadState('networkidle');assert.equal(await page.locator('.page-content').count(),1);assert.equal(await page.locator('.page-content').innerText().then(t=>/Something went wrong|Endpoint not found/.test(t)),false,route);results.push(route+' rendered');}
await page.goto('http://127.0.0.1:3000/app/pipeline');await page.waitForLoadState('networkidle');await page.screenshot({path:'screenshots/pipeline-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:3000/app');await page.getByRole('button',{name:'Toggle color theme'}).click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.waitForLoadState('networkidle');await page.screenshot({path:'screenshots/dashboard-dark.png',fullPage:true});results.push('Dark mode persists after reload');
await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForLoadState('networkidle');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile page must not overflow');await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'Contacts',exact:true}).click();await page.getByRole('heading',{name:'Contacts',exact:true}).waitFor();results.push('Mobile menu navigation works');
await page.goto('http://127.0.0.1:3000/app');await page.getByRole('button',{name:'Toggle color theme'}).click();await page.waitForLoadState('networkidle');await page.screenshot({path:'screenshots/dashboard-mobile.png',fullPage:true});
await page.goto('http://127.0.0.1:3000');await page.waitForLoadState('networkidle');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile home must not overflow');await page.screenshot({path:'screenshots/home-mobile.png',fullPage:true});results.push('Mobile public page has no horizontal overflow');
assert.deepEqual(errors,[]);results.push('No browser runtime errors');
await writeFile('BROWSER-TEST-RESULTS.json',JSON.stringify({passed:results.length,results,errors},null,2));console.log(JSON.stringify({passed:results.length,results,errors},null,2));
}catch(e){await page.screenshot({path:'screenshots/browser-failure.png',fullPage:true});await writeFile('work/browser-failure.txt',await page.locator('body').innerText());throw e;}finally{await browser.close();}

