import {db} from '../server/db.js';
import {id,passwordHash,token} from '../server/security.js';
import {createWorkspace} from '../server/plans.js';
import {writeFile} from 'node:fs/promises';
try{if(process.env.NODE_ENV==='production')throw Error('Development seed is disabled in production');if(await db('users').where({email:'demo@leadnest.local'}).first()){console.log('Development seed already exists.');process.exitCode=0;}else{const password='Demo-'+token().slice(0,18);await db.transaction(async k=>{const u=id();await k('users').insert({id:u,name:'Alex Morgan',email:'demo@leadnest.local',password_hash:passwordHash(password),verified:true});const w=await createWorkspace(k,u,'Acme Studio · Demo');const pipe=await k('pipelines').where({workspace_id:w}).first();const names=[['Olivia Rhye','Layers','Qualified',145000],['Phoenix Baker','Sisyphus','Proposal',240000],['Lana Steiner','Catalog','New',85000],['Demi Wilkinson','Circooles','Contacted',120000],['Drew Cano','Hourglass','Won',310000],['Natali Craig','Command+R','New',75000],['Orlando Diggs','Quotient','Qualified',195000],['Andi Lane','Goodwell','Lost',90000]];
for(const [i,[name,company,status,value]] of names.entries()){const row={id:id(),workspace_id:w,name,company,email:name.toLowerCase().replace(' ','.')+'@example.com',assigned_to:u,status,value_paise:value*100,currency:'INR',source:['Website','Referral','LinkedIn'][i%3],tags:i%2?'SaaS':'Design',notes:'Development sample record. Replace with your own customer data.',pipeline_id:pipe.id,follow_up_at:new Date(Date.now()+(i-2)*86400000),created_at:new Date(Date.now()-(8-i)*86400000)};await k('leads').insert(row);await k('contacts').insert({...row,id:id()});await k('companies').insert({...row,id:id(),name:company});await k('deals').insert({...row,id:id(),name:company+' · Growth package'});}
for(const [i,name] of ['Send proposal to Sisyphus','Follow up with Olivia','Prepare discovery call','Review quarterly pipeline'].entries()){const tid=id();await k('tasks').insert({id:tid,workspace_id:w,name,assigned_to:u,status:i===3?'Completed':'Open',priority:i===0?'High':'Normal',due_at:new Date(Date.now()+(i-1)*86400000)});if(i!==3)await k('reminders').insert({id:id(),workspace_id:w,user_id:u,task_id:tid,due_at:new Date(Date.now()+(i-1)*86400000)});}
await k('activities').insert({id:id(),workspace_id:w,user_id:u,description:'Development sample workspace created',record_type:'workspace',record_id:w});await k('email_drafts').insert({id:id(),workspace_id:w,user_id:u,recipient:'',subject:'A quick follow-up',body:'Hello,\n\nThank you for our conversation. Here is a quick summary of the next steps.\n\nBest regards,',is_template:true});});await writeFile('DEVELOPMENT-ACCESS.txt','LOCAL DEVELOPMENT ONLY\nEmail: demo@leadnest.local\nPassword: '+password+'\n\nThis is a Free-plan demo workspace. Use Billing to simulate a ₹1 trial without real money.\n');console.log('Demo created. Credentials saved locally in DEVELOPMENT-ACCESS.txt.');}}finally{await db.destroy();}

